#
# Travis CI recipe to build docker image.
#

sudo: required

language: generic

services:
  - docker

script:
  - echo "Starting build of Docker image..."
  - docker build --no-cache --pull -t fedorovd/docker-firefox:$TRAVIS_JOB_ID .
